#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'
require 'set'

module AutoFreeze
  def initialize(*args)
    super
    freeze
  end
end

Point = Struct.new(:x, :y) { include AutoFreeze }
Equation = Struct.new(:slope, :y_intercept) { include AutoFreeze }

def parse_input(input)
  JSON.parse(input).map do |coord|
    Point.new(*coord)
  end
end

def linear_eq(point_a, point_b)
  a, b = point_a.x < point_b.x ? [point_a, point_b] : [point_b, point_a]
  slope = (a.y - b.y) / (a.x - b.x).to_f
  y_intercept = a.y - (slope * a.x)
  Equation.new(slope, y_intercept)
end

def find_lines(points)
  lines = Hash.new(Set.new.freeze)
  points.combination(2).each do |a, b|
    eq = linear_eq(a, b)
    unless eq.slope.nan? || eq.slope.infinite?
      lines[eq] += [a, b]
    end
  end
  lines
end

puts find_lines(parse_input($stdin.read)).values.map(&:size).max
