name:                get-in-line

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  get-in-line-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - get-in-line
